Update charter.md
abetterinternet/ppm-specification pull request #165
Opened 2021-11-12 06:29 UTC by ShivanKaul

Amend charter to allow for alternative privacy-preserving measurement techniques that address some desired use cases.

2021-11-12 15:57 UTC, chris-wood approved these changes

2021-11-17 18:20 UTC, cjpatton approved these changes

2021-11-19 04:23 UTC, ekr requested changes
LGTM with one change

2021-11-19 04:23 UTC, ekr commented on charter.md
> +- Client submission of individual measurements
```suggestion
- Client submission of individual measurements, potentially along with proofs of validity
```

Avoiding the non sequiter later.

2021-11-29 20:12 UTC, merged