Add HMAC-SHA256 tag to all Request/Response messages.
abetterinternet/ppm-specification pull request #197
Opened 2022-03-04 23:49 UTC by BranLwyd

Previously these were inconsistently applied between different messages.
I introduce a new `collect_auth_key`, distinct from the existing
`agg_auth_key`, for collect messages.

I think we could get away with only authenticating the request messages
(leaning on TLS to provide authentication for the responses); I'd be
amenable to that, but my understanding is that we don't want to rely on
the properties of the underlying channel, so I went ahead and specified
authentication tags for both request & response messages.

2022-03-05 01:46 UTC, cjpatton requested changes
Tagging the AggregateShareReq with the key shared by the aggregators makes sense. (The fact that this was missing was an oversight.)

However I think we should sync up before making changes to the collect flow. I envisioned using mutual TLS for this, Mozilla might have a different idea.

2022-03-05 01:46 UTC, cjpatton commented on draft-gpew-priv-ppm.md
> +  collect flow.
This key would only need to be shared by the collector and leader. The helper doesn't need this key, does it?

2022-03-07 17:14 UTC, BranLwyd commented
> Tagging the AggregateShareReq with the key shared by the aggregators makes sense. (The fact that this was missing was an oversight.)
> 
> However I think we should sync up before making changes to the collect flow. I envisioned using mutual TLS for this, Mozilla might have a different idea.

OK, I've removed the `tag` from the `Collect{Req,Resp}` for now. mTLS would work too, and I'll be happy to go with whatever is determined by group consensus.

2022-03-07 17:52 UTC, divergentdave approved these changes

2022-03-07 19:43 UTC, cjpatton approved these changes

2022-03-08 17:01 UTC, merged